"""add_sector_to_patients

Revision ID: f333a0a9f95d
Revises: a64af0e2d514
Create Date: 2026-06-04 19:08:53.679831

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f333a0a9f95d"
down_revision: Union[str, Sequence[str], None] = "a64af0e2d514"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patients", sa.Column("sector", sa.String(length=10), nullable=True))
    op.create_index(op.f("ix_patients_sector"), "patients", ["sector"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patients_sector"), table_name="patients")
    op.drop_column("patients", "sector")
    # ### end Alembic commands ###
